version: "3.8"

services:
  app:
    image: ${IMAGE_URI}
    container_name: flow-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network

networks:
  app_network:
    external: true
